# Generated by Django 5.0.2 on 2024-06-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='puzzle_rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='solved_puzzles',
            field=models.ManyToManyField(blank=True, to='puzzles.puzzle'),
        ),
    ]
