# Generated by Django 5.0.2 on 2024-07-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
        ('users', '0002_customuser_puzzle_rating_customuser_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='incorrectly_solved_puzzles',
            field=models.ManyToManyField(blank=True, related_name='incorrectly_solved_by_users', to='puzzles.puzzle'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='solved_puzzles',
            field=models.ManyToManyField(blank=True, related_name='solved_by_users', to='puzzles.puzzle'),
        ),
    ]
