version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=django-insecure-+p-p19s#aau(r&#-kr5jh)$$t5)wn7z!6-=4a#vyx+oa$$vmxrfe
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=database2005

volumes:
  postgres_data: