# Generated by Django 5.0.2 on 2024-12-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
