# Generated by Django 5.0.2 on 2024-12-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
